/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "تحديد خريطة",
        selectMapHint: "اختر الخريطة ستوفر هذه الأداة وتعيدها",
        captureSection: "ماذا ينقذ",
        captureViewpoint: "نقطة المراقبة (المركز، الحجم، التناوب، آلة تصوير ثلاثية الأبعاد)",
        captureLayers: "الرؤية والظلم",
        captureFilters: "تعاريف وتعاريف",
        captureBasemap: "خريطة أساس",
        captureTime: "مدى الوقت (موقع الانزلاق الزمني)",
        captureGraphics: "الرسم البياني (بما في ذلك الرسم/الرسم)",
        limitsSection: "القيود والبدء",
        maxInstances: "الحد الأقصى لحالات الإنقاذ",
        maxInstancesHint: "لا يوجد حد",
        defaultInstance: "اضغط على هذه الحالة في البداية",
        defaultInstanceHint: "قومي بتصنيع الاسم الدقيق لمؤسسة إنقاذ أو اتركي فارغة",
        defaultInstanceNone: "لا شيء",
        help: "المساعدة",
        showHelpGuide: "دليل المساعدة",
        showTheQuestionMarkButtonThat: "اظهر زر التساؤل الذي يفتح المرشد"
      })
    }
  }
})
