/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Избор на карта",
        selectMapHint: "Изберете карта джаджа този инструмент ще запази и възстанови.",
        captureSection: "Какво да запишете",
        captureViewpoint: "Гледната точка (център, мащаб, въртене, 3D камера)",
        captureLayers: "Видимост и непрозрачност на слой",
        captureFilters: "Определения и етикети",
        captureBasemap: "Базова карта",
        captureTime: "Времеви обхват (времева позиция на плъзгача)",
        captureGraphics: "Графика (включително Draw/Sketch)",
        limitsSection: "Граници и стартиране",
        maxInstances: "Максимално записани случаи",
        maxInstancesHint: "Настроен на 0 без ограничение.",
        defaultInstance: "Зареждане на този пример при стартиране",
        defaultInstanceHint: "Напишете точното име на записан случай или оставете празно.",
        defaultInstanceNone: "Няма",
        help: "Помощ",
        showHelpGuide: "Показване на ръководство за помощ",
        showTheQuestionMarkButtonThat: "Показване на бутона въпрос-марка, която отваря джаджа помощ ръководство"
      })
    }
  }
})
