/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Vybrat mapu",
        selectMapHint: "Vyberte widget mapy, který nástroj uloží a obnoví.",
        captureSection: "Co uložit",
        captureViewpoint: "Viewpoint (střed, měřítko, rotace, 3D kamera)",
        captureLayers: "Viditelnost vrstvy a opacita",
        captureFilters: "Výrazy a etikety definice",
        captureBasemap: "Podkladová mapa",
        captureTime: "Rozsah času (poloha posuvníku času)",
        captureGraphics: "Grafika (včetně kresby / skeče)",
        limitsSection: "Omezení a spuštění",
        maxInstances: "Maximální uložené instance",
        maxInstancesHint: "Nastavit na 0 bez omezení.",
        defaultInstance: "Načíst tuto instanci při spuštění",
        defaultInstanceHint: "Napište přesný název uloženého instance, nebo nechte prázdné.",
        defaultInstanceNone: "Žádný",
        help: "Nápověda",
        showHelpGuide: "Zobrazit nápovědu",
        showTheQuestionMarkButtonThat: "Zobrazit tlačítko question- mark, které otevře nápovědu widget"
      })
    }
  }
})
