/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Επιλέξτε έναν χάρτη",
        selectMapHint: "Επιλέξτε το γραφικό συστατικό χάρτη αυτό το εργαλείο θα σώσει και να αποκαταστήσει.",
        captureSection: "Τι να αποθηκεύσετε",
        captureViewpoint: "Προβολή (κέντρο, κλίμακα, περιστροφή, τρισδιάστατη κάμερα)",
        captureLayers: "Ορατότητα και αδιαφάνεια στρώματος",
        captureFilters: "Ορισμός εκφράσεων και ετικετών",
        captureBasemap: "Υπόβαθρο",
        captureTime: "Χρονική έκταση (θέση κύλισης του χρόνου)",
        captureGraphics: "Γραφικά (συμπεριλαμβανομένου του Draw/Sketch)",
        limitsSection: "Όρια και εκκίνηση",
        maxInstances: "Μέγιστες αποθηκευμένες περιπτώσεις",
        maxInstancesHint: "Ρυθμίστε στο 0 χωρίς όριο.",
        defaultInstance: "Φόρτωση αυτής της περίπτωσης κατά την εκκίνηση",
        defaultInstanceHint: "Πληκτρολογήστε το ακριβές όνομα ενός αποθηκευμένου στιγμιότυπου, ή αφήστε κενό.",
        defaultInstanceNone: "Καθόλου",
        help: "Βοήθεια",
        showHelpGuide: "Εμφάνιση οδηγού βοήθειας",
        showTheQuestionMarkButtonThat: "Εμφάνιση του κουμπιού ερωτηματολογίου που ανοίγει τον οδηγό βοήθειας widget"
      })
    }
  }
})
