/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Seleccionar un mapa",
        selectMapHint: "Elija el widget del mapa esta herramienta guardará y restaurará.",
        captureSection: "Qué salvar",
        captureViewpoint: "Punto de vista (centro, escala, rotación, cámara 3D)",
        captureLayers: "Visibilidad y opacidad de capas",
        captureFilters: "Expresiones y etiquetas de definición",
        captureBasemap: "Mapa base",
        captureTime: "Plazo (Posición deslizante de tiempo)",
        captureGraphics: "Gráficos (incluyendo Dibujo/Esqueje)",
        limitsSection: "Límites y puesta en marcha",
        maxInstances: "Casos máximos salvados",
        maxInstancesHint: "Se establece a 0 sin límite.",
        defaultInstance: "Cargar esta instancia en la startup",
        defaultInstanceHint: "Escribe el nombre exacto de una instancia salvada, o deja en blanco.",
        defaultInstanceNone: "Ninguna",
        help: "Ayuda",
        showHelpGuide: "Mostrar guía de ayuda",
        showTheQuestionMarkButtonThat: "Mostrar el botón de la marca de preguntas que abre el widget guía de ayuda"
      })
    }
  }
})
