/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Vali kaart",
        selectMapHint: "Vali kaardi vidin, mida see tööriist salvestab ja taastab.",
        captureSection: "Mida päästa",
        captureViewpoint: "Vaadepunkt (keskpunkt, skaala, pööramine, 3D-kaamera)",
        captureLayers: "Kihi nähtavus ja hägusus",
        captureFilters: "Määratlusväljendid ja -märgised",
        captureBasemap: "Aluskaart",
        captureTime: "Aja ulatus (ajaliuguri asend)",
        captureGraphics: "Graafika (sh joonis/joonis)",
        limitsSection: "Piirangud ja käivitamine",
        maxInstances: "Salvestatud eksemplaride maksimum",
        maxInstancesHint: "Määra 0-ks ilma piiranguta.",
        defaultInstance: "Selle protsessi laadimine käivitamisel",
        defaultInstanceHint: "Kirjuta salvestatud protsessi täpne nimi või jäta tühjaks.",
        defaultInstanceNone: "Puudub",
        help: "Abi",
        showHelpGuide: "Abijuhendi näitamine",
        showTheQuestionMarkButtonThat: "Küsimusemärgi nupu näitamine, mis avab vidina abi juhendi"
      })
    }
  }
})
