/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Valitse kartta",
        selectMapHint: "Valitse kartta widget tämä työkalu tallentaa ja palauttaa.",
        captureSection: "Mitä tallentaa",
        captureViewpoint: "Viewpoint (keskus, asteikko, kierto, 3D-kamera)",
        captureLayers: "Tason näkyvyys ja opasiteetti",
        captureFilters: "Määritelmän ilmaukset ja merkinnät",
        captureBasemap: "Taustakartta",
        captureTime: "Aikaväli (aikaliukurin sijainti)",
        captureGraphics: "Grafiikka",
        limitsSection: "Rajat ja käynnistys",
        maxInstances: "Tallennettujen tapausten enimmäismäärä",
        maxInstancesHint: "Aseta nolla rajattomaksi.",
        defaultInstance: "Lataa tämä esimerkki käynnistettäessä",
        defaultInstanceHint: "Kirjoita tallennetun instanssin tarkka nimi tai jätä tyhjäksi.",
        defaultInstanceNone: "Ei mitään",
        help: "Ohje",
        showHelpGuide: "Näytä ohje",
        showTheQuestionMarkButtonThat: "Näytä kysymys-merkki-painike, joka avaa widget ohjeen"
      })
    }
  }
})
