/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Sélectionner une carte",
        selectMapHint: "Choisissez le widget de carte que cet outil enregistrera et restaurera.",
        captureSection: "Que sauver",
        captureViewpoint: "Point de vue (centre, échelle, rotation, caméra 3D)",
        captureLayers: "Visibilité et opacité de la couche",
        captureFilters: "Définitions et étiquettes",
        captureBasemap: "Fond de carte",
        captureTime: "Durée (position du curseur de temps)",
        captureGraphics: "Graphiques (y compris dessins/cartouches)",
        limitsSection: "Limites et démarrage",
        maxInstances: "instances maximales enregistrées",
        maxInstancesHint: "Régler à 0 pour aucune limite.",
        defaultInstance: "Charger cette instance au démarrage",
        defaultInstanceHint: "Saisissez le nom exact d'une instance enregistrée ou laissez-le vide.",
        defaultInstanceNone: "Aucun",
        help: "Aide",
        showHelpGuide: "Afficher le guide d'aide",
        showTheQuestionMarkButtonThat: "Afficher le bouton question-marque qui ouvre le guide d'aide du widget"
      })
    }
  }
})
