/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "בחר מפה",
        selectMapHint: "בחר את המפה וידגום את הכלי הזה יחסוך ויחזור.",
        captureSection: "מה לחסוך",
        captureViewpoint: "Viewpoint (מרכז, סולם, סיבוב, מצלמה 3D)",
        captureLayers: "נוכחות שכבתית ואופי",
        captureFilters: "המונחים and labels",
        captureBasemap: "מפת בסיס",
        captureTime: "זמן (זמן שקופיות)",
        captureGraphics: "גרפיקה (כולל צייר / Sketch)",
        limitsSection: "גבולות וסטארט-אפ",
        maxInstances: "מקסימום מקרים לחסוך",
        maxInstancesHint: "הגדרת 0 ללא הגבלה.",
        defaultInstance: "עקבו אחרי Startup",
        defaultInstanceHint: "הקלד את השם המדויק של מקרה הציל, או להשאיר ריק.",
        defaultInstanceNone: "ללא",
        help: "עזרה",
        showHelpGuide: "מדריך עזרה",
        showTheQuestionMarkButtonThat: "הצג את לחצן סימן שאלה פותח את מדריך העזרה widget"
      })
    }
  }
})
