/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Térkép kiválasztása",
        selectMapHint: "Válassza ki a térkép widget ez az eszköz menteni és visszaállítani.",
        captureSection: "Mit kell megmenteni",
        captureViewpoint: "Képpont (központ, skála, forgás, 3D kamera)",
        captureLayers: "A réteg láthatósága és átlátszatlansága",
        captureFilters: "Meghatározási kifejezések és címkék",
        captureBasemap: "Alaptérkép",
        captureTime: "Az idő kiterjedése (időcsúszós helyzet)",
        captureGraphics: "Grafika (beleértve a rajzot / rajzot)",
        limitsSection: "Határértékek és indítás",
        maxInstances: "Maximális megtakarított esetek",
        maxInstancesHint: "Beállítva 0-ra, nincs limit.",
        defaultInstance: "Az eset betöltése indításkor",
        defaultInstanceHint: "Írja be a mentett példány pontos nevét, vagy hagyja üresen.",
        defaultInstanceNone: "Egyik sem",
        help: "Súgó",
        showHelpGuide: "Segítőútmutató megjelenítése",
        showTheQuestionMarkButtonThat: "Megjeleníti a kérdőjel gombot, amely megnyitja a widget súgó útmutatót"
      })
    }
  }
})
