/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Pilih peta",
        selectMapHint: "Pilih widget peta yang akan disimpan dan dikembalikan.",
        captureSection: "Apa yang harus disimpan",
        captureViewpoint: "Titik lihat (tengah, skala, rotasi, kamera 3D)",
        captureLayers: "undo-type",
        captureFilters: "Ekspresi dan label definisi",
        captureBasemap: "Peta Dasar",
        captureTime: "Jarak waktu (posisi penggeser waktu)",
        captureGraphics: "Grafik (termasuk Gambar / Sketch)",
        limitsSection: "Batas dan awalan",
        maxInstances: "Maksimum disimpan misalnya",
        maxInstancesHint: "Set ke 0 tanpa batas.",
        defaultInstance: "Muat instansi ini pada startup",
        defaultInstanceHint: "Ketik nama yang tepat dari instansi yang disimpan, atau tinggalkan kosong.",
        defaultInstanceNone: "Tidak Ada",
        help: "Bantuan",
        showHelpGuide: "Tampilkan panduan bantuan",
        showTheQuestionMarkButtonThat: "Tampilkan tombol tanya-tandai yang membuka panduan bantuan widget"
      })
    }
  }
})
