/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Selezionare una mappa",
        selectMapHint: "Scegliere il widget mappa questo strumento salverà e ripristinare.",
        captureSection: "Cosa salvare",
        captureViewpoint: "Punto di vista (centro, scala, rotazione, fotocamera 3D)",
        captureLayers: "Visibilità del livello e opacità",
        captureFilters: "Espressioni e etichette di definizione",
        captureBasemap: "Mappa di base",
        captureTime: "Portata del tempo (posizione del cursore del tempo)",
        captureGraphics: "Grafica (compreso Disegno/Sketch)",
        limitsSection: "Limiti e avvio",
        maxInstances: "Massime istanze salvate",
        maxInstancesHint: "Impostare a 0 per nessun limite.",
        defaultInstance: "Caricare questa istanza all'avvio",
        defaultInstanceHint: "Digitare il nome esatto di un'istanza salvata o lasciare vuoto.",
        defaultInstanceNone: "Nessuno",
        help: "Guida",
        showHelpGuide: "Mostra la guida",
        showTheQuestionMarkButtonThat: "Mostra il pulsante di punto interrogativo che apre la guida di aiuto widget"
      })
    }
  }
})
