/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "マップの選択",
        selectMapHint: "このツールが保存して復元するマップウィジェットを選択します。",
        captureSection: "保存する",
        captureViewpoint: "視点(中心、スケール、回転、3Dカメラ)",
        captureLayers: "層の可視性および不透明度",
        captureFilters: "定義式とラベル",
        captureBasemap: "ベースマップ",
        captureTime: "時間範囲(時間のスライダーの位置)",
        captureGraphics: "グラフィック(ドロー/スケッチを含む)",
        limitsSection: "制限とスタートアップ",
        maxInstances: "最大保存インスタンス",
        maxInstancesHint: "制限なしに設定します。",
        defaultInstance: "起動時にこのインスタンスをロードする",
        defaultInstanceHint: "保存したインスタンスの正確な名前を入力するか、空白のままにします。",
        defaultInstanceNone: "なし",
        help: "ヘルプ",
        showHelpGuide: "ヘルプガイドを表示",
        showTheQuestionMarkButtonThat: "ウィジェットヘルプガイドを開く質問のボタンを表示する"
      })
    }
  }
})
