/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "맵 선택",
        selectMapHint: "이 도구는 저장하고 복원 할지도 위젯을 선택합니다.",
        captureSection: "견적 요청",
        captureViewpoint: "Viewpoint (센터, 스케일, 회전, 3D 카메라)",
        captureLayers: "층 가시성과 불투명",
        captureFilters: "정의 표현 및 라벨",
        captureBasemap: "베이스맵",
        captureTime: "시간 (시간 slider 위치)",
        captureGraphics: "그래픽 (Draw/Sketch 포함)",
        limitsSection: "제한 및 시작",
        maxInstances: "최대 저장된 인스턴스",
        maxInstancesHint: "제한이 없습니다.",
        defaultInstance: "이 인스턴스를 시작",
        defaultInstanceHint: "저장된 인스턴스의 정확한 이름을 입력하거나 공백을 남깁니다.",
        defaultInstanceNone: "없음",
        help: "도움말",
        showHelpGuide: "공지사항",
        showTheQuestionMarkButtonThat: "위젯 도움말 가이드를 열 수있는 질문 표시 버튼"
      })
    }
  }
})
