/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Pasirinkti žemėlapį",
        selectMapHint: "Choose the map widget this tool will save and restore.",
        captureSection: "What to save",
        captureViewpoint: "Viewpoint (center, scale, rotation, 3D camera)",
        captureLayers: "Layer visibility and opacity",
        captureFilters: "Definition expressions and labels",
        captureBasemap: "Pagrindo žemėlapis",
        captureTime: "Time extent (time slider position)",
        captureGraphics: "Graphics (including Draw/Sketch)",
        limitsSection: "Limits and startup",
        maxInstances: "Maximum saved instances",
        maxInstancesHint: "Set to 0 for no limit.",
        defaultInstance: "Load this instance on startup",
        defaultInstanceHint: "Type the exact name of a saved instance, or leave blank.",
        defaultInstanceNone: "Nėra",
        help: "Pagalba",
        showHelpGuide: "Rodyti pagalbos vadovą",
        showTheQuestionMarkButtonThat: "Rodyti klausimų žymėjimo mygtuką, kuris atveria valdikliui skirtą pagalbos vadovą"
      })
    }
  }
})
