/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Pasirinkti žemėlapį",
        selectMapHint: "Pasirinkite žemėlapio valdikliui šis įrankis bus išsaugoti ir atkurti.",
        captureSection: "Ką išsaugoti",
        captureViewpoint: "Žiūrėti (centras, skalė, rotacija, 3D kamera)",
        captureLayers: "Sluoksnio matomumas ir neskaidrumas",
        captureFilters: "Apibrėžimai ir etiketės",
        captureBasemap: "Pagrindo žemėlapis",
        captureTime: "Laiko tarpas (laiko slankiklio padėtis)",
        captureGraphics: "Grafika (įskaitant piešimą / brėžinį)",
        limitsSection: "Ribos ir paleidimas",
        maxInstances: "Maksimalūs įrašyti atvejai",
        maxInstancesHint: "Nustatyti į 0 be limito.",
        defaultInstance: "Įkelti šį egzempliorių paleidžiant",
        defaultInstanceHint: "Įveskite tikslų įrašyto atvejo pavadinimą arba palikite tuščią.",
        defaultInstanceNone: "Nėra",
        help: "Pagalba",
        showHelpGuide: "Rodyti pagalbos vadovą",
        showTheQuestionMarkButtonThat: "Rodyti klausimų žymėjimo mygtuką, kuris atveria valdikliui skirtą pagalbos vadovą"
      })
    }
  }
})
