/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Izvēlēties karti",
        selectMapHint: "Izvēlieties kartes logdaļu šis rīks saglabās un atjaunos.",
        captureSection: "Ko saglabāt",
        captureViewpoint: "Skata punkts (centrs, skala, rotācija, 3D kamera)",
        captureLayers: "Slāņa redzamība un necaurredzamība",
        captureFilters: "Definīciju izteiksmes un etiķetes",
        captureBasemap: "Pamatkarte",
        captureTime: "Laika apjoms (laika slīdņa pozīcija)",
        captureGraphics: "Grafika (tostarp zīmēšana/ierakstīšana)",
        limitsSection: "Ierobežojumi un starts",
        maxInstances: "Maksimums saglabāto gadījumu",
        maxInstancesHint: "Iestatīt uz 0 bez ierobežojuma.",
        defaultInstance: "Ielādēt šo instanci pie palaišanas",
        defaultInstanceHint: "Ievadiet precīzu saglabātās instances nosaukumu vai atstājiet tukšu.",
        defaultInstanceNone: "Neviens",
        help: "Palīdzība",
        showHelpGuide: "Rādīt palīdzības ceļvedi",
        showTheQuestionMarkButtonThat: "Rādīt jautājumu zīmes pogu, kas atver logdaļu palīdzības rokasgrāmatu"
      })
    }
  }
})
