/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Een kaart selecteren",
        selectMapHint: "Kies de kaart widget deze tool zal opslaan en herstellen.",
        captureSection: "Wat moet worden opgeslagen",
        captureViewpoint: "Viewpoint (center, schaal, rotatie, 3D camera)",
        captureLayers: "Laagzicht en dekking",
        captureFilters: "Definitieuitdrukkingen en etiketten",
        captureBasemap: "Basiskaart",
        captureTime: "Tijdsafstand (positie van de tijdregelaar)",
        captureGraphics: "Grafieken (inclusief Draw/Sketch)",
        limitsSection: "Limieten en opstarten",
        maxInstances: "Maximum opgeslagen instanties",
        maxInstancesHint: "Zet op 0 zonder limiet.",
        defaultInstance: "Deze instantie laden bij opstarten",
        defaultInstanceHint: "Typ de exacte naam van een opgeslagen instantie, of laat leeg.",
        defaultInstanceNone: "Geen",
        help: "Hulp",
        showHelpGuide: "Hulplijn tonen",
        showTheQuestionMarkButtonThat: "De knop met het vraagteken tonen die de hulplijn widget opent"
      })
    }
  }
})
