/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Velg et kart",
        selectMapHint: "Velg kart widget dette verktøyet vil lagre og gjenopprette.",
        captureSection: "Hva å spare",
        captureViewpoint: "Visingspunkt (senter, skala, rotasjon, 3D-kamera)",
        captureLayers: "Lagets synlighet og åpenhet",
        captureFilters: "Definisjon uttrykk og etiketter",
        captureBasemap: "Bakgrunnskart",
        captureTime: "Tidsdimensjon (tidglidestilling)",
        captureGraphics: "Grafikk (inkludert Draw/Sketch)",
        limitsSection: "Grenser og oppstart",
        maxInstances: "Maksimalt lagrede tilfeller",
        maxInstancesHint: "Sett til 0 for ingen grense.",
        defaultInstance: "Last denne instansen ved oppstart",
        defaultInstanceHint: "Skriv det nøyaktige navnet på en lagret instans, eller la tom.",
        defaultInstanceNone: "Ingen",
        help: "Hjelp",
        showHelpGuide: "Vis hjelpguide",
        showTheQuestionMarkButtonThat: "Vis spørsmålsmerkeknappen som åpner widget-hjelpeguiden"
      })
    }
  }
})
