/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Wybierz mapę",
        selectMapHint: "Wybierz widget mapy to narzędzie zapisze i przywróci.",
        captureSection: "Co zapisać",
        captureViewpoint: "Viewpoint (środek, skala, obrót, kamera 3D)",
        captureLayers: "Widoczność i nieprzezroczystość warstwy",
        captureFilters: "Wyrażenia i etykiety definicji",
        captureBasemap: "Mapa bazowa",
        captureTime: "Zakres czasu (pozycja suwaka czasu)",
        captureGraphics: "Grafika (w tym rysowanie / rysowanie)",
        limitsSection: "Limity i startup",
        maxInstances: "Maksymalne zapisane instancje",
        maxInstancesHint: "Ustaw na 0 bez limitu.",
        defaultInstance: "Wczytaj tę instancję na starcie",
        defaultInstanceHint: "Wpisz dokładną nazwę zapisanej instancji lub pozostaw puste.",
        defaultInstanceNone: "Brak",
        help: "Pomoc",
        showHelpGuide: "Pokaż przewodnik pomocy",
        showTheQuestionMarkButtonThat: "Pokaż przycisk question- mark, który otwiera przewodnik pomocy widget"
      })
    }
  }
})
