/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Selecionar um mapa",
        selectMapHint: "Escolha o widget do mapa que esta ferramenta irá salvar e restaurar.",
        captureSection: "O que salvar",
        captureViewpoint: "Ponto de visão (centro, escala, rotação, câmera 3D)",
        captureLayers: "Visibilidade e opacidade da camada",
        captureFilters: "Expressões de definição e rótulos",
        captureBasemap: "Mapa Base",
        captureTime: "Extensão do tempo (posição da barra de tempo)",
        captureGraphics: "Gráficos (incluindo desenho/cenário)",
        limitsSection: "Limites e inicialização",
        maxInstances: "Máximas instâncias salvas",
        maxInstancesHint: "Pronto para zero sem limite.",
        defaultInstance: "Carregar esta instância na inicialização",
        defaultInstanceHint: "Digite o nome exato de uma instância salva, ou deixe em branco.",
        defaultInstanceNone: "Nenhum",
        help: "Ajuda",
        showHelpGuide: "Mostre guia de ajuda",
        showTheQuestionMarkButtonThat: "Mostre o botão de ponto de interrogação que abre o guia de ajuda do widget"
      })
    }
  }
})
