/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Selecionar um mapa",
        selectMapHint: "Choose the map widget this tool will save and restore.",
        captureSection: "What to save",
        captureViewpoint: "Viewpoint (center, scale, rotation, 3D camera)",
        captureLayers: "Layer visibility and opacity",
        captureFilters: "Definition expressions and labels",
        captureBasemap: "Mapa Base",
        captureTime: "Time extent (time slider position)",
        captureGraphics: "Graphics (including Draw/Sketch)",
        limitsSection: "Limits and startup",
        maxInstances: "Maximum saved instances",
        maxInstancesHint: "Set to 0 for no limit.",
        defaultInstance: "Load this instance on startup",
        defaultInstanceHint: "Type the exact name of a saved instance, or leave blank.",
        defaultInstanceNone: "Nenhum",
        help: "Ajuda",
        showHelpGuide: "Mostre guia de ajuda.",
        showTheQuestionMarkButtonThat: "Mostre o botão de ponto de interrogação que abre o guia de ajuda do widget."
      })
    }
  }
})
