/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Selectaţi o hartă",
        selectMapHint: "Alegeți widget harta acest instrument va salva și restabili.",
        captureSection: "Ce este de salvat",
        captureViewpoint: "Potrivit (centru, scară, rotație, cameră 3D)",
        captureLayers: "Vizibilitatea și opacitatea straturilor",
        captureFilters: "Expresii și etichete de definiție",
        captureBasemap: "Hartă fundal",
        captureTime: "Întindere în timp (poziție în timp)",
        captureGraphics: "Grafică (inclusiv desen/schelet)",
        limitsSection: "Limite și pornire",
        maxInstances: "Cazuri salvate maxime",
        maxInstancesHint: "Setat la 0 pentru nici o limită.",
        defaultInstance: "Încărcaţi acest caz la pornire",
        defaultInstanceHint: "Scrieţi numele exact al unei instanţe salvate sau lăsaţi-l gol.",
        defaultInstanceNone: "Niciunul",
        help: "Ajutor",
        showHelpGuide: "Arată ghidul de ajutor",
        showTheQuestionMarkButtonThat: "Arată butonul semn de întrebare care deschide ghidul de ajutor widget"
      })
    }
  }
})
