/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Выберите карту",
        selectMapHint: "Выберите виджет карты, этот инструмент сохранит и восстановит.",
        captureSection: "Что экономить",
        captureViewpoint: "Точка зрения (центр, масштаб, вращение, 3D-камера)",
        captureLayers: "Видимость и непрозрачность слоя",
        captureFilters: "Выражения определений и ярлыки",
        captureBasemap: "Базовая карта",
        captureTime: "Временной интервал (time slider position)",
        captureGraphics: "Графика (включая рисунок/набросок)",
        limitsSection: "Пределы и стартап",
        maxInstances: "Максимально сохраненные экземпляры",
        maxInstancesHint: "Установите 0 без ограничения.",
        defaultInstance: "Загрузите этот экземпляр для стартапа",
        defaultInstanceHint: "Введите точное имя сохраненного экземпляра или оставьте пустой.",
        defaultInstanceNone: "Нет",
        help: "Справка",
        showHelpGuide: "Показать справочник",
        showTheQuestionMarkButtonThat: "Покажите кнопку вопрос-марка, которая открывает руководство по помощи виджета"
      })
    }
  }
})
