/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Vybrať mapu",
        selectMapHint: "Vyberte mapový prvok, ktorý tento nástroj uloží a obnoví.",
        captureSection: "Čo zachrániť",
        captureViewpoint: "Zobraziť bod (centrum, mierka, otáčanie, 3D kamera)",
        captureLayers: "Viditeľnosť a opacita vrstvy",
        captureFilters: "Výrazy a označenia pojmov",
        captureBasemap: "Podkladová mapa",
        captureTime: "Časový rozsah (poloha posuvníka)",
        captureGraphics: "Grafika (vrátane výkresu/seku)",
        limitsSection: "Limity a spustenie",
        maxInstances: "Maximálne uložené inštancie",
        maxInstancesHint: "Nastaviť na 0 bez limitu.",
        defaultInstance: "Načítať tento prípad pri štarte",
        defaultInstanceHint: "Zadajte presný názov uloženého inštancie, alebo nechajte prázdne.",
        defaultInstanceNone: "Žiadne",
        help: "Pomocník",
        showHelpGuide: "Zobraziť návod na pomoc",
        showTheQuestionMarkButtonThat: "Zobraziť tlačidlo otázniku, ktoré otvorí sprievodcu pomocníkom"
      })
    }
  }
})
