/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Izberi karto",
        selectMapHint: "Izberite gradnik zemljevida, ki ga bo to orodje shranilo in obnovilo.",
        captureSection: "Kaj rešiti",
        captureViewpoint: "Vidna točka (center, lestvica, vrtenje, 3D kamera)",
        captureLayers: "Vidnost plasti in prosojnost",
        captureFilters: "Definicijski izrazi in oznake",
        captureBasemap: "Temeljna karta",
        captureTime: "Časovni obseg (mesto časovnega drsnika)",
        captureGraphics: "Grafika (vključno z vlečenjem/vlačenjem)",
        limitsSection: "Omejitve in zagon",
        maxInstances: "Največji shranjeni primeri",
        maxInstancesHint: "Nastavi na 0 brez omejitev.",
        defaultInstance: "Naloži ta primer ob zagonu",
        defaultInstanceHint: "Vnesite točno ime shranjenega izvoda ali pustite prazno.",
        defaultInstanceNone: "Brez",
        help: "Pomoč",
        showHelpGuide: "Prikaži vodnik za pomoč",
        showTheQuestionMarkButtonThat: "Prikaži gumb z vprašanji, ki odpre widget pomoč vodnik"
      })
    }
  }
})
