/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Välj en karta",
        selectMapHint: "Välj kartan widget detta verktyg kommer att spara och återställa.",
        captureSection: "Vad att spara",
        captureViewpoint: "Viewpoint (center, skala, rotation, 3D-kamera)",
        captureLayers: "Layer synlighet och opacity",
        captureFilters: "Definitionsuttryck och etiketter",
        captureBasemap: "Baskarta",
        captureTime: "Tidsgrad (tidsreglageposition)",
        captureGraphics: "Grafik (inklusive Draw/Sketch)",
        limitsSection: "Begränsningar och startup",
        maxInstances: "Maximalt sparade instanser",
        maxInstancesHint: "Ställ in 0 för ingen gräns.",
        defaultInstance: "Ladda detta exempel på start",
        defaultInstanceHint: "Skriv det exakta namnet på ett sparat instans eller lämna tomt.",
        defaultInstanceNone: "Inga",
        help: "Hjälp",
        showHelpGuide: "Visa hjälp guide",
        showTheQuestionMarkButtonThat: "Visa frågemärke knappen som öppnar widget hjälp guide"
      })
    }
  }
})
