/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "เลือกแผนที่",
        selectMapHint: "เลือกวิดเจ็ตของแผนที่ เครื่องมือนี้จะทําการบันทึกและเรียกคืนค่า",
        captureSection: "จะบันทึกอะไร",
        captureViewpoint: "มุมมอง (กลาง, ขนาด, หมุน, กล้อง 3 มิติ)",
        captureLayers: "เลเยอร์",
        captureFilters: "นิพจน์การแบ่งแยกและป้าย",
        captureBasemap: "แผนที่ฐาน",
        captureTime: "จํากัดเวลา (ตําแหน่งแถบเวลา)",
        captureGraphics: "กราฟิก (รวมการวาด/ สคีตด้วย)",
        limitsSection: "จํากัด และ เริ่ม ต้น",
        maxInstances: "จํานวนตัวอักษรที่จะบันทึกสูงสุด",
        maxInstancesHint: "กําหนดเป็น 0 ไม่จํากัด",
        defaultInstance: "โหลดโปรแกรมนี้เมื่อเริ่มการทํางาน",
        defaultInstanceHint: "พิมพ์ชื่อของโพรเซสที่บันทึกหรือปล่อยว่างไว้",
        defaultInstanceNone: "ไม่มี",
        help: "ตัวช่วย",
        showHelpGuide: "แสดงคําแนะนํา",
        showTheQuestionMarkButtonThat: "แสดงปุ่ม เครื่องหมายคําถามที่เปิดวิดเจ็ตคําแนะนํา"
      })
    }
  }
})
