/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Harita seç",
        selectMapHint: "Harita widget'ı bu aracı seçin ve restore edin.",
        captureSection: "Ne kurtarmak için",
        captureViewpoint: "Viewpoint (merkez, ölçek, rotasyon, 3D kamera)",
        captureLayers: "Katman görünürlüğü ve opakity",
        captureFilters: "Açıklama ifadeleri ve etiketler",
        captureBasemap: "Altlık Harita",
        captureTime: "Zaman aralığı (zaman kaydırıcı pozisyonu)",
        captureGraphics: "Grafik ( Draw/Sketch dahil)",
        limitsSection: "Limitler ve başlangıç",
        maxInstances: "En çok kaydedilen örnekler",
        maxInstancesHint: "Limit için 0'a ayarlayın.",
        defaultInstance: "Bu örneği başlangıç üzerine yükleme",
        defaultInstanceHint: "Kurtarılan bir örneğin tam adını yazın veya boş bırakın.",
        defaultInstanceNone: "Hiçbiri",
        help: "Yardım",
        showHelpGuide: "Show help guide",
        showTheQuestionMarkButtonThat: "Widget'ı açan soru işaret düğmesine göster"
      })
    }
  }
})
