/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Вибрати карту",
        selectMapHint: "Виберіть віджет карти, цей інструмент збереже і відновлює.",
        captureSection: "Як зберегти",
        captureViewpoint: "Точка зору (центр, вага, обертання, 3D камера)",
        captureLayers: "Шарова видимість і непрозорість",
        captureFilters: "Визначення виразів та етикеток",
        captureBasemap: "Базова карта",
        captureTime: "Час (часова позиція слайдера)",
        captureGraphics: "Графіка (включаючи Draw/Sketch)",
        limitsSection: "Ліміти та стартапи",
        maxInstances: "Максимальна кількість збережених екземплярів",
        maxInstancesHint: "Набір до 0 без обмеження.",
        defaultInstance: "Завантаження цього екземпляра на старті",
        defaultInstanceHint: "Введіть точну назву збереженого екземпляра або залишити порожній.",
        defaultInstanceNone: "Немає",
        help: "Довідка",
        showHelpGuide: "Показати посібник",
        showTheQuestionMarkButtonThat: "Показати натис-mark, який відкриває посібник з підтримки віджету"
      })
    }
  }
})
