/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Chọn bản đồ",
        selectMapHint: "Chọn ô điều khiển bản đồ công cụ này sẽ lưu và phục hồi.",
        captureSection: "Để cứu cái gì?",
        captureViewpoint: "Xem (trung, tỷ lệ, Quay, máy ảnh 3D)",
        captureLayers: "Tầm nhìn và độ mờ đục của lớp",
        captureFilters: "Định nghĩa biểu thức và nhãn",
        captureBasemap: "Bản đồ nền",
        captureTime: "Thời gian",
        captureGraphics: "Đồ họa (bao gồm Draw/Sketch)",
        limitsSection: "Giới hạn và khởi chạy",
        maxInstances: "Lần lưu tối đa",
        maxInstancesHint: "Thiết lập 0 không giới hạn.",
        defaultInstance: "Tải tiến trình này khi khởi chạy",
        defaultInstanceHint: "Gõ tên chính xác của trường hợp đã lưu, hoặc để trống.",
        defaultInstanceNone: "Không có",
        help: "Trợ giúp",
        showHelpGuide: "Hiện hướng dẫn trợ giúp",
        showTheQuestionMarkButtonThat: "Hiển thị nút đánh dấu câu hỏi để mở hướng dẫn trợ giúp ô điều khiển"
      })
    }
  }
})
