/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "Chọn bản đồ",
        selectMapHint: "Choose the map widget this tool will save and restore.",
        captureSection: "What to save",
        captureViewpoint: "Viewpoint (center, scale, rotation, 3D camera)",
        captureLayers: "Layer visibility and opacity",
        captureFilters: "Definition expressions and labels",
        captureBasemap: "Bản đồ nền",
        captureTime: "Time extent (time slider position)",
        captureGraphics: "Graphics (including Draw/Sketch)",
        limitsSection: "Limits and startup",
        maxInstances: "Maximum saved instances",
        maxInstancesHint: "Set to 0 for no limit.",
        defaultInstance: "Load this instance on startup",
        defaultInstanceHint: "Type the exact name of a saved instance, or leave blank.",
        defaultInstanceNone: "Không có",
        help: "Trợ giúp",
        showHelpGuide: "Hiện hướng dẫn trợ giúp",
        showTheQuestionMarkButtonThat: "Hiển thị nút đánh dấu câu hỏi để mở hướng dẫn trợ giúp ô điều khiển"
      })
    }
  }
})
