/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "选择地图",
        selectMapHint: "选择此工具将保存和恢复的地图部件 。",
        captureSection: "怎样保存",
        captureViewpoint: "视图点( 中心、 尺度、 旋转、 3D 相机)",
        captureLayers: "层可见度和不透明",
        captureFilters: "定义表达式和标签",
        captureBasemap: "底图",
        captureTime: "时间范围(时间滑动器位置)",
        captureGraphics: "图形(包括 Draw/Sketch)",
        limitsSection: "限制和启动",
        maxInstances: "最大保存实例",
        maxInstancesHint: "无限设定为 0 。",
        defaultInstance: "启动时装入此实例",
        defaultInstanceHint: "键入保存实例的确切名称, 或留空 。",
        defaultInstanceNone: "无",
        help: "帮助",
        showHelpGuide: "显示帮助指南",
        showTheQuestionMarkButtonThat: "显示打开部件帮助指南的问题标记按钮"
      })
    }
  }
})
