/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "選擇地圖",
        selectMapHint: "選擇此工具會儲存和恢復的地圖元件 。",
        captureSection: "保存什么",
        captureViewpoint: "檢視點( 中心、 尺度、 旋轉、 3D 相機)",
        captureLayers: "層面能見度與透明度",
        captureFilters: "定義表示和標籤",
        captureBasemap: "底圖",
        captureTime: "時間範圍( 時間滑動位置)",
        captureGraphics: "圖像( 包括 Draw/ Sketch)",
        limitsSection: "限制和啟動",
        maxInstances: "最大保存的例",
        maxInstancesHint: "設置為 0 不限值 。",
        defaultInstance: "啟動時載入此實體",
        defaultInstanceHint: "輸入已儲存實體的确切名稱, 或是留空白 。",
        defaultInstanceNone: "無",
        help: "說明",
        showHelpGuide: "顯示說明指南",
        showTheQuestionMarkButtonThat: "顯示開啟元件說明指導的問題標鍵"
      })
    }
  }
})
