/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMap: "選擇地圖",
        selectMapHint: "Choose the map widget this tool will save and restore.",
        captureSection: "What to save",
        captureViewpoint: "Viewpoint (center, scale, rotation, 3D camera)",
        captureLayers: "Layer visibility and opacity",
        captureFilters: "Definition expressions and labels",
        captureBasemap: "底圖",
        captureTime: "Time extent (time slider position)",
        captureGraphics: "Graphics (including Draw/Sketch)",
        limitsSection: "Limits and startup",
        maxInstances: "Maximum saved instances",
        maxInstancesHint: "Set to 0 for no limit.",
        defaultInstance: "Load this instance on startup",
        defaultInstanceHint: "Type the exact name of a saved instance, or leave blank.",
        defaultInstanceNone: "無",
        help: "說明",
        showHelpGuide: "顯示說明指南",
        showTheQuestionMarkButtonThat: "顯示開啟元件說明指導的問題標鍵"
      })
    }
  }
})
